GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVG9ueSIsImlhdCI6MTY4MDI2OTU4MCwiZXhwIjoxNjgwMjY5NTk1fQ.QEkcUTeLFQrgQDILYpY-PeeOxPNzX2CeSCoZh-ufTQw

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Tony",
    "password": "password"
}

###

# POST http://localhost:3000/users/login
# Content-Type: application/json

# {
#     "name": "Tony",
#     "password": "password"
# }

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "Tony",
    "password": "password"
}

###

POST http://localhost:3000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVG9ueSIsImlhdCI6MTY4MDI5MTEyOX0.Z3e8WOl6uTD8jKICUAz_7fDiwU7TaB4GsDDJISv-7vA"
}

###

DELETE http://localhost:3000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVG9ueSIsImlhdCI6MTY4MDI2OTM0OH0.1gJtqLY5Ry7t1U03GMrtQdfn2e4hmuE5PAuIIo4AXHM"
}